# app2.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: app2-html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Application 2</title>
    <style>
      body { background-color: #fff0f5; font-family: sans-serif; text-align: center; }
      h1 { color: #db7093; }
    </style>
    </head>
    <body>
    <h1>Welcome to Application 2!</h1>
    <p>You reached me via the /app2 path.</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort # Or ClusterIP
