apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-ingress-cluster # Choose a unique name for your cluster
  region: us-east-1

vpc:
  nat:
    gateway: Single # For cost optimization in a lab environment

managedNodeGroups:
- name: my-eks-nodegroup
  instanceType: t3.medium # Or t2.medium for lower cost
  minSize: 2
  maxSize: 3
  desiredCapacity: 2
  volumeSize: 20
  privateNetworking: false # Keep as false for simplicity in a lab; nodes need internet access
  # Important: This will create an IAM role for your EKS worker nodes.
  # eksctl handles attaching the AmazonEKSWorkerNodePolicy and AmazonEC2ContainerRegistryReadOnly policies.
